"""Canonical catalogue -> Rust, Science Lab data and reviewer-friendly skill guide."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
DATA = json.loads((HERE / 'catalogue.json').read_text())
def generate(check=False):
    skills, combos = DATA['skills'], DATA['combos']
    assert len(skills) == 75 and len(combos) == 50
    assert len({s['id'] for s in skills}) == 75
    for s in skills:
        assert len(s['tokens']) == len(s['charge']) and sum(s['charge']) == s['cost']
        assert all(c > 0 for c in s['charge']) and s['science'] in range(3)
    assert len({(s['science'], tuple(s['tokens'])) for s in skills}) == 75
    for c in combos:
        assert 1 <= len(c['steps']) <= 5 and all(0 <= i < 75 for i in c['steps'])
        assert sum(skills[i]['cost'] for i in c['steps']) <= 100
    q = lambda x: json.dumps(x, ensure_ascii=False)
    rust = '// Generated by Claude outputs/unified_theory/generate.py. Do not edit.\n'
    rust += '#[derive(Debug)]\npub struct Skill { pub id: &\'static str, pub name: &\'static str, pub science: usize, pub role: &\'static str, pub tokens: &\'static [&\'static str], pub charge: &\'static [u32], pub cooldown: usize }\n'
    rust += 'pub static SKILLS: &[Skill] = &[\n'
    for s in skills:
        rust += 'Skill { id: '+q(s['id'])+', name: '+q(s['name'])+', science: '+str(s['science'])+', role: '+q(s['role'])+', tokens: &['+', '.join(map(q, s['tokens']))+'], charge: &'+str(s['charge'])+', cooldown: '+str(s['cooldown'])+' },\n'
    rust += '];\npub static COMBOS: &[(&str, &[usize])] = &[\n'
    for c in combos:
        rust += '('+q(c['name'])+', &'+str(c['steps'])+'),\n'
    rust += '];\n'
    js = '// Generated. Canonical source: Claude outputs/unified_theory/catalogue.json\n(function(root){ const data='+json.dumps(DATA, separators=(',', ':'))+'; if(typeof module!=="undefined") module.exports=data; else root.ScienceData=data; })(typeof globalThis!=="undefined"?globalThis:this);\n'
    md = '# The Unified Theory: skill catalogue\n\nGenerated from `Claude outputs/unified_theory/catalogue.json`. All skills are available at every rank. Charges are CU per token, in recipe order.\n\n| ID | Skill | Activation | CU | Role / result | Cooldown |\n|---|---|---|---|---|---|\n'
    for s in skills:
        md += f"| {s['id']} | {s['name']} | "+' → '.join(f'{t}({c})' for t,c in zip(s['tokens'],s['charge']))+f" | {s['cost']} | {s['role']}: {s['effect']} | {s['cooldown']/60:g}s |\n"
    md += '\n## Experiment recipes\n\nThese are templates, not extra multipliers. Every output shares its experiment budget. Invalid geometry, expired prerequisites and critical charge failures cancel remaining stages and refund their reservations.\n\n'
    for n,c in enumerate(combos,1):
        md += f"{n}. **{c['name']}** — "+' → '.join(skills[i]['id']+' '+skills[i]['name'] for i in c['steps'])+f" ({sum(skills[i]['cost'] for i in c['steps'])} CU).\n"
    outputs = {'native/tfm2_custom_ai/src/unified_theory_data.rs':rust, 'editor/unified-theory-data.js':js, 'docs/unified-theory-catalogue.md':md}
    for path, content in outputs.items():
        p = ROOT/path
        if check: assert p.read_text() == content, f'Stale generated file: {p}'
        else: p.write_text(content)
    print('75 unique skills; 50 bounded recipes; generated files current' if check else 'Generated 75 skills and 50 recipes')
if __name__ == '__main__':
    import sys
    generate('--check' in sys.argv)
